// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvmmppyvqiqfgefsoamb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bW1wcHl2cWlxZmdlZnNvYW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTk1MjEsImV4cCI6MjA2NTg3NTUyMX0.WQSwqWUZ_zfpBUGHv5E35F3flQaKbB5o9DzZcnpfxC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);